# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b72f20426360b79c2777589a08f17178b82aaee3678478b1f896aa137baa8d18a18d0d857b80405733b2981acf3632c914a18b4ac63db82c0300400ebd1586c3

test:
  secret_key_base: 33b4f6db5ae6655ee5d7a756a19454961529ea0098a0dd909a8caacada6b42b2dd3a0dec18198608eada551b89633f56a8adcd213bafdf05172fed057ea743ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
